### ISSUE TITLE
Feature request: wireless mouse on/off state detection

### ISSUE THREAD

**Issue by GenaBitu** [user501254/TouchpadIndicator#13]
I have a wireless mouse (Logitech M325) and have the dongle permanently plugged in. Would it be possible to detect the mouse on/off state and use it to turn the touchpad on/off? Currently I have to pull the dongle out, turn off automatic touchpad disabling and put it back in when I am somewhere without the mouse...
Thank you!

**Comment by k1T4eR** [comment]
+1 It'd be great feature.
For example, handle it by changing power state of logitech device.

**Comment by user501254** [comment]
@GenaBitu @k1T4eR 
As far as I know, this is not plausible since such On/Off state can not be detected.
To explain further, even when the mouse is physically switched off but the dongle is plugged in; it would come up in the list of input devices.
Additionally, @GenaBitu can you elaborate on your need to turn off automatic touchpad disabling when you are somewhere without the mouse? IMO, just unplugging the dongle should work leaving the auto-disable settings as it is.

**Comment by GenaBitu** [comment]
That's a shame, that would really be an awesome feature

Elaborating: When I am somewhere without the mouse, I don't want to unplug the dongle because I am afraid of losing it 😄...

Sifting through the internet:
https://lekensteyn.nl/logitech-unifying.html#ltunify
could this be used? It would only fix this for logitech devices but since the vast majority of those uses the same dongle, that should work for all of those....

**Comment by toastbrotch** [comment]
+1
